theme: minima
title: Bubble
author: Rafael Alcalde
email: rafalcalde@live.com.mx
description: This page is pure data porn, here you can skim trough some of the best contect in tech, and use our tools to analyze data and make it more visual.


# social links
twitter_username: alcalde_rafael # DO NOT include the @ character, or else the build will fail!
github_username:  rafalcalde # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
